# Generated by Django 2.0 on 2018-08-19 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataChunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('datachunk_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.DataChunk')),
                ('pinned', models.BooleanField(default=False)),
            ],
            bases=('store.datachunk',),
        ),
        migrations.AddField(
            model_name='datachunk',
            name='related',
            field=models.ManyToManyField(related_name='_datachunk_related_+', to='store.DataChunk'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('topic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.Topic')),
                ('due', models.DateTimeField(null=True)),
                ('wait', models.DateTimeField(null=True)),
            ],
            bases=('store.topic',),
        ),
    ]
