# Generated by Django 2.0 on 2018-08-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20180819_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datachunk',
            name='related',
            field=models.ManyToManyField(related_name='_datachunk_related_+', to='store.DataChunk'),
        ),
    ]
