# Generated by Django 2.0.6 on 2018-09-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_task_complete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='topic',
            name='action_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='due',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='wait',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
