# Generated by Django 2.0.6 on 2018-09-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20180908_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='wait',
            field=models.DateField(blank=True, null=True),
        ),
    ]
