# Generated by Django 2.1 on 2018-09-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20180908_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='wait',
            new_name='ready',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='action_required',
        ),
    ]
