# Generated by Django 2.0.6 on 2019-02-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20180910_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datachunk',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
