# Generated by Django 2.1.4 on 2019-02-24 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20190220_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textchunk',
            name='title',
        ),
    ]
