# Generated by Django 2.1.4 on 2019-02-24 14:35

from django.db import migrations


def description_to_textchunk(apps, schema_editor):
    Topic = apps.get_model('store', 'Topic')
    TextChunk = apps.get_model('store', 'TextChunk')

    for topic in Topic.objects.all():
        if topic.text:
            TextChunk.objects.create(topic=topic, text='# Description\n' + topic.text)


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_textchunk_title'),
    ]

    operations = [
        migrations.RunPython(description_to_textchunk),
        migrations.RemoveField(
            model_name='datachunk',
            name='text',
        ),
    ]
