# Generated by Django 2.1.4 on 2019-02-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_datachunk_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='importance',
            field=models.IntegerField(default=0),
        ),
    ]
