# Generated by Django 2.0.6 on 2019-03-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='textchunk',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
